### ISSUE TITLE
来支持一下（大一时候的维客的兄弟）

### ISSUE THREAD

**Issue by LeadroyaL** [Armour/Magic-Tower-Qt#1]
我也非常喜欢魔塔，曾经在写一个安卓的魔塔，后来弃坑了；
玩了几十个版本的魔塔，经常混迹魔塔贴吧。。。
翻github突然翻到你了，估计你对我都没印象了 =_=
又去翻了一下你qq空间，感觉好厉害呀，兄弟加油！！

**Comment by Armour** [comment]
哇谢谢支持~ 感觉自己写游戏自己玩的时候会特别开心2333 （而且还可以作弊2333
