### ISSUE TITLE
windeployqt.exe deploy win7 app failed

### ISSUE THREAD

**Issue by snapedumbledore** [Armour/Magic-Tower-Qt#3]
Qt Creator 4.5.0
MinGW 5.3.0(32bit)
I get the error"driver not loaded" and "this application has requested Runtime to terminate it in an unusual way",after i get the exe.
I google a lot but nothing happen.
Can you help me ?
Thanks a lot.

**Comment by Armour** [comment]
Sorry I don't have computer with Windows 7 now, can't really help to reproduce this problem, but from what you said "driver not loaded", should be something related to driver library missing, you can take look at the error message and figure out which driver library is missing and simply install it should fix that.
